#!/bin/bash --login
#PBS -l walltime=10:00:00
#PBS -l select=1:ncpus=16
#PBS -N 1-2DPCoA
#PBS -A d411-training
#PBS -j oe

echo "Setting temporary Qiime directory"
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

echo "loading Qiime environment"
conda deactivate
conda activate qiime1

echo "creating cd to output directory"
mkdir -p ~/output/Meta2_PCoA/
cd ~/output/Meta2_PCoA/

echo "Creating 2D Plot"

time make_2d_plots.py -i ~/output/Meta2Divers/output/bdiv_even40000/unweighted_unifrac_pc.txt -m ~/Metadata2.tsv -o ./UnweightedPC

echo "Calculation Complete"

echo "closing environment"
conda deactivate
