#!/bin/bash --login
#PBS -l walltime=10:00:00
#PBS -l select=1:ncpus=16
#PBS -N CompCat
#PBS -A d411-training
#PBS -j oe

echo "Setting temporary Qiime directory"
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

echo "loading Qiime environment"
conda deactivate
conda activate qiime1

echo "creating cd to output directory"
mkdir -p ~/output/Meta2_Comp/
cd ~/output/Meta2_Comp/

echo "Calculating Diversity..."
echo "Running anoism"

time compare_categories.py --method anosim -i ~/output/Meta2Divers/output/bdiv_even40000/unweighted_unifrac_dm.txt -m ~/Metadata2.tsv -c Rind_or_Core -o ./Anoism/Rind_or_Core -n 99

echo "Running ADONIS"
time compare_categories.py --method adonis -i ~/output/Meta2Divers/output/bdiv_even40000/unweighted_unifrac_dm.txt -m ~/Metadata2.tsv -c Rind_or_Core -o ./Adonis/Rind_or_Core

echo "Calculation Complete"

echo "closing environment"
conda deactivate

### end script


                                                   
